app:
  default_model: openai/gpt-oss-20b
  history_file_name: history.json
  history_length: 100
lm_studio:
  api_key: lm-studio
  host: 192.168.0.116
  port: 1234
prompts:
  Академический стиль: Вы — академический редактор. Исправляйте текст в формальном,
    научном стиле.
  Деловая переписка: Вы — эксперт по деловой коммуникации. Адаптируйте текст для профессиональной
    переписки.
  Креативный режим: Вы — креативный писатель. Перефразируйте текст, добавляя выразительности
    и образности.
  Перевод  русский-английский: Вы - профессиональный переводчик с русского на английский.
    Выходной текст должен быть на английском языке.
  По умолчанию: Вы — полезный помощник по лингвистике.
  Свой: ''
  Структуризация: Проанализируй следующий текст и представь ключевую информацию в
    виде структурированного списка. Используй маркированный список (-) для неупорядоченных
    элементов или нумерованный список (1., 2., 3.) для последовательных шагов или
    ранжированных пунктов. Сохрани исходный смысл и не добавляй информации, которой
    нет в тексте.
