app:
  default_model: openai/gpt-oss-20b
  history_file_name: history.json
  history_length: 100
lm_studio:
  api_key: lm-studio
  host: 192.168.0.116
  port: 1234
prompts:
  По умолчанию: Вы — полезный и точный инструмент исправляющий текст. Проведите операции над текстом выше не добавляя ничего лишнего.
  Академический стиль: Вы — академический редактор. Исправляйте текст в формальном,
    научном стиле.
  Деловая переписка: Вы — эксперт по деловой коммуникации. Адаптируйте текст для профессиональной
    переписки.
  Сокращение: Сократи текст сохранив смысл.
  Энергичный текст: Перефразируй текст в более энергичной форме.
  Исправление: Выступи в роли профессионального редактора. Исправь все грамматические, пунктуационные и стилистические ошибки в тексте ниже. Строго сохрани исходный смысл, структуру абзацев и авторскую интонацию. Не добавляй новую информацию и не сокращай текст. В ответе выведи ТОЛЬКО исправленный вариант, без приветствий и пояснений.
  Креативный режим: Вы — креативный писатель. Перефразируйте текст, добавляя выразительности
    и образности.
  Перевод  RU-EN: You are a professional Russian-to-English translator. Respond only in English.
  Свой: ''
  Структуризация: Проанализируй следующий текст и представь ключевую информацию в
    виде структурированных списков с заголовками . Используй маркированный список (-) для неупорядоченных
    элементов или нумерованный список (1., 2., 3.) для последовательных шагов или
    ранжированных пунктов. Сохрани исходный смысл и не добавляй информации, которой
    нет в тексте.
  Перевод EN-RU: Вы - профессиональный переводчик с английского на русский. Выходной текст должен быть на русском языке.
